apiVersion: apps/v1
kind: Deployment
metadata:
  name: paymybuddy-backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: paymybuddy-backend
  template:
    metadata:
      labels:
        app: paymybuddy-backend
    spec:
      containers:
        - name: paymybuddy-backend
          image: votre-utilisateur/paymybuddy-backend:latest
          envFrom:
            - configMapRef:
                name: paymybuddy-config
            - secretRef:
                name: paymybuddy-secret
          ports:
            - containerPort: 8080
