apiVersion: v1
kind: Service
metadata:
  name: paymybuddy-db
spec:
  selector:
    app: paymybuddy-db
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306
---
apiVersion: v1
kind: Service
metadata:
  name: paymybuddy-backend
spec:
  selector:
    app: paymybuddy-backend
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: LoadBalancer
